# Generated by Django 3.1.7 on 2021-02-23 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='table',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
