# Generated by Django 3.1.7 on 2021-03-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20210224_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_table',
            old_name='complete',
            new_name='status',
        ),
    ]
